### ISSUE TITLE
Parameterize access to glean app channels

### ISSUE THREAD

**Issue by relud** [mozilla/lookml-generator#15]
for example `fenix` has 5 tables for `baseline`:
```yaml
fenix:
  canonical_app_name: Firefox for Android
  views:
    baseline:
    - channel: release
      table: mozdata.org_mozilla_firefox.baseline
    - channel: beta
      table: mozdata.org_mozilla_firefox_beta.baseline
    - channel: nightly
      table: mozdata.org_mozilla_fenix.baseline
    - channel: nightly
      table: mozdata.org_mozilla_fenix_nightly.baseline
    - channel: nightly
      table: mozdata.org_mozilla_fennec_aurora.baseline
```

and we need to accept a parameter for `channel`.

~Where `channel` is enough to uniquely identify one table, then we might be able to template `sql_table_name`.~

~In cases like fenix nightly baseline, we have 3 tables and they all have the same schema, we can use a `derived_table` section with `sql` like `SELECT * FROM ... UNION ALL SELECT * FROM ...`. This actually requires that we sort the schemas so they match, but you can sort the schemas with a short downtime via a table copy operation. If we have a case with multiple tables where the schemas don't actually match (different columns, but no conflicting types), then we could also specify all of the columns in the `derived_table`'s `sql`, adding `NULL` where necessary.~

edit: `channel` is enough to uniquely identify one table
